all:compile	run
compile:
	g++ -I ./include/ -o ./lib/Basket.o -c ./src/Basket.cpp
	g++ -I ./include/ -o ./lib/Ball.o -c ./src/Ball.cpp
	g++ -I ./include/ -o ./lib/BasketManager.o -c ./src/BasketManager.cpp
	g++ -I ./include  -o ./bin/Program ./src/Program.cpp
run:
	./bin/program
